# Generated by Django 3.2.24 on 2024-03-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numLot', models.CharField(help_text='Número do Lote', max_length=13)),
                ('contractLot', models.CharField(max_length=19)),
                ('descriptionLot', models.CharField(max_length=250)),
                ('priceLot', models.CharField(max_length=13)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
